# Generated by Django 5.2.3 on 2025-06-24 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KDSStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('station_type', models.CharField(choices=[('hot_kitchen', 'Hot Kitchen'), ('cold_kitchen', 'Cold Kitchen'), ('prep', 'Prep Station'), ('beverage', 'Beverage Station')], default='hot_kitchen', help_text='Type of kitchen station', max_length=50, verbose_name='station type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this station is currently active', verbose_name='is active')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional station-specific data in JSON format', verbose_name='additional metadata')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kds_stations', to='branches.branch', verbose_name='branch')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
            ],
            options={
                'verbose_name': 'kds station',
                'verbose_name_plural': 'kds stations',
                'ordering': ('branch', 'name'),
            },
        ),
        migrations.CreateModel(
            name='KDSItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the kitchen item', max_length=20, verbose_name='status')),
                ('kitchen_notes', models.TextField(blank=True, help_text='Notes from kitchen staff about this item', verbose_name='kitchen notes')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the item was completed', null=True, verbose_name='completed at')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional item-specific data in JSON format', verbose_name='additional metadata')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kds_item', to='sales.orderitem', verbose_name='order item')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kds_items', to='kds.kdsstation', verbose_name='station')),
            ],
            options={
                'verbose_name': 'kds item',
                'verbose_name_plural': 'kds items',
                'ordering': ('-created_at', 'status'),
            },
        ),
        migrations.AddIndex(
            model_name='kdsstation',
            index=models.Index(fields=['branch', 'is_active'], name='kds_kdsstat_branch__48573d_idx'),
        ),
        migrations.AddIndex(
            model_name='kdsstation',
            index=models.Index(fields=['branch', 'station_type'], name='kds_kdsstat_branch__f12edf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kdsstation',
            unique_together={('branch', 'name')},
        ),
        migrations.AddIndex(
            model_name='kdsitem',
            index=models.Index(fields=['station', 'status'], name='kds_kdsitem_station_b4a2d2_idx'),
        ),
        migrations.AddIndex(
            model_name='kdsitem',
            index=models.Index(fields=['created_at'], name='kds_kdsitem_created_3248be_idx'),
        ),
        migrations.AddIndex(
            model_name='kdsitem',
            index=models.Index(fields=['completed_at'], name='kds_kdsitem_complet_268996_idx'),
        ),
    ]
