# Generated by Django 5.2.3 on 2025-06-28 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('branches', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Who approved this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
        migrations.AddField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(help_text='Branch where expense was incurred', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='branches.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='expense',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AddField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Employee associated with this expense (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='employees.employee', verbose_name='employee'),
        ),
        migrations.AddField(
            model_name='expense',
            name='last_modified_by',
            field=models.ForeignKey(help_text='User who last modified this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_expenses', to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
        migrations.AddField(
            model_name='expenseaccount',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AddField(
            model_name='expenseaccount',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent account (for hierarchical accounts)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subaccounts', to='accounting.expenseaccount', verbose_name='parent account'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='default_account',
            field=models.ForeignKey(blank=True, help_text='Default expense account for this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_categories', to='accounting.expenseaccount', verbose_name='default account'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='accounting.expensecategory', verbose_name='parent category'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(help_text='Expense category', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='accounting.expensecategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who issued the gift card', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_gift_cards', to=settings.AUTH_USER_MODEL, verbose_name='issued by'),
        ),
    ]
