# Generated by Django 5.2.3 on 2025-06-24 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='issued_to',
            field=models.ForeignKey(help_text='Customer who received the gift card', on_delete=django.db.models.deletion.PROTECT, related_name='gift_cards', to='crm.customer', verbose_name='issued to'),
        ),
        migrations.AddField(
            model_name='giftcardredemption',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AddField(
            model_name='giftcardredemption',
            name='gift_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='accounting.giftcard', verbose_name='gift card'),
        ),
    ]
