# Generated by Django 5.2.3 on 2025-07-08 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_initial'),
        ('inventory', '0005_purchaseorder_invoice_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Related purchase order, if this expense is for a purchase order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_expenses', to='inventory.purchaseorder'),
        ),
    ]
