# Generated by Django 5.2.3 on 2025-07-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='track_inventory',
            field=models.BooleanField(default=False, help_text='Enable inventory tracking for this menu item', verbose_name='track inventory'),
        ),
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=False, help_text='Enable inventory tracking for this product', verbose_name='track inventory'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('initial', 'Initial'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer'), ('waste', 'Waste'), ('production', 'Production')], max_length=20, verbose_name='transaction type'),
        ),
    ]
