# Generated by Django 5.2.3 on 2025-07-01 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0003_menuitem_track_inventory_product_track_inventory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branchstock',
            unique_together={('product', 'branch')},
        ),
        migrations.AddConstraint(
            model_name='branchstock',
            constraint=models.UniqueConstraint(condition=models.Q(('menu_item', None), _negated=True), fields=('menu_item', 'branch'), name='unique_menuitem_branch'),
        ),
    ]
