# Generated by Django 5.2.3 on 2025-06-28 04:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0003_purchaseorder_purchaseorderitem_stockcount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchstock',
            options={'ordering': ('-content_type__model', 'branch__name'), 'verbose_name': 'branch stock', 'verbose_name_plural': 'branch stock'},
        ),
        migrations.AlterUniqueTogether(
            name='branchstock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='branchstock',
            name='content_type',
            field=models.ForeignKey(default=1, limit_choices_to={'model__in': ('product', 'menuitem')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchstock',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_stock', to='inventory.menuitem', verbose_name='menu item'),
        ),
        migrations.AddField(
            model_name='branchstock',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branchstock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_stock', to='inventory.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='branchstock',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use product/default price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='selling price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True, verbose_name='barcode'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True, verbose_name='barcode'),
        ),
        migrations.AlterUniqueTogether(
            name='branchstock',
            unique_together={('content_type', 'object_id', 'branch')},
        ),
    ]
