# Generated by Django 5.2.3 on 2025-06-28 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_branchstock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchstock',
            options={'ordering': ('branch__name',), 'verbose_name': 'branch stock', 'verbose_name_plural': 'branch stock'},
        ),
        migrations.AlterUniqueTogether(
            name='branchstock',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='branchstock',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='branchstock',
            name='object_id',
        ),
    ]
