# Generated by Django 5.2.3 on 2025-07-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_purchaseorder_invoice_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='menu/items/images/'),
        ),
    ]
