# Generated by Django 5.2.3 on 2025-06-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_add_branchstock_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='branchstock',
            name='unique_product_branch_stock',
        ),
        migrations.RemoveConstraint(
            model_name='branchstock',
            name='unique_menu_item_branch_stock',
        ),
    ]
