# Generated by Django 5.2.3 on 2025-06-28 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('inventory', '0002_initial'),
        ('loyalty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='customers', to='inventory.allergy'),
        ),
        migrations.AddField(
            model_name='customer',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='loyalty.loyaltyprogram'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='user account'),
        ),
        migrations.AddField(
            model_name='customertag',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='customers', to='crm.customertag', verbose_name='tags'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='crm_custome_created_1d27ae_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['updated_at'], name='crm_custome_updated_7389ad_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_code'], name='crm_custome_custome_aaeed4_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type'], name='crm_custome_custome_82c91f_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['alternate_phone'], name='crm_custome_alterna_dc8d04_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company_name'], name='crm_custome_company_a7d034_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['loyalty_program'], name='crm_custome_loyalty_73695f_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['preferred_contact_method'], name='crm_custome_preferr_2f0d26_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['marketing_opt_in'], name='crm_custome_marketi_0cf4cd_idx'),
        ),
    ]
